[features]
seeds = false
skip-lint = false

[programs.localnet]
awe = "AWacB995GvfsqCJxbfZtLWvSp9EhB72aN2Xd84X3haZN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
token = "yarn run ts-node client/setup_awe_token.ts"
metadata = "yarn run ts-node client/setup_awe_metadata.ts"
agent = "yarn run ts-node client/test_awe_agent.ts"
mint = "yarn run ts-node client/mint_awe.ts"
wallet = "yarn run ts-node client/create_wallet.ts"
batch_transfer = "yarn run ts-node client/batch_transfer_awe.ts"

[toolchain]
anchor_version = "0.30.1"
